// Turns the designer's task-icons/task-icons.json into a small module the client imports.
// Run after replacing the folder:  node scripts/gen-icons.mjs   (and copy the PNGs to client/public/task-icons/)
import fs from 'node:fs';

const src = JSON.parse(fs.readFileSync(new URL('../task-icons/task-icons.json', import.meta.url), 'utf8'));
const icons = src.icons.map((i) => ({
  kind: i.kind,
  // Tasks are keyed by their number (1-22), sabotage devices by their letter (L, C, W).
  key: i.id,
  file: i.file,
  highlight: i.highlightFile,
  w: i.sizeInMapPx.w,
  h: i.sizeInMapPx.h,
  spots: i.kind === 'task' ? [{ x: i.position[0], y: i.position[1], wall: i.wall }] : i.positions,
}));
const out = '// GENERATED by scripts/gen-icons.mjs from task-icons/task-icons.json. Do not edit by hand.\n'
  + '// Sizes and positions are in design map px (820 x 690). Each PNG has 4 map px of padding (10 for the highlight).\n'
  + `export default ${JSON.stringify(icons)};\n`;
fs.writeFileSync(new URL('../client/src/shared/task-icons.data.js', import.meta.url), out);
console.log(`wrote ${icons.length} icons`);
