// Turns the designer's task-icons/task-icons.json into a small module the client imports.
// Run after replacing the folder:  node scripts/gen-icons.mjs   (and copy the PNGs to client/public/task-icons/;
// the plant PNGs are copied for you)
import fs from 'node:fs';

const src = JSON.parse(fs.readFileSync(new URL('../task-icons/task-icons.json', import.meta.url), 'utf8'));
const icons = src.icons.map((i) => ({
  kind: i.kind,
  // Tasks are keyed by their number (1-22), sabotage devices by their letter (L, C, W).
  key: i.id,
  file: i.file,
  highlight: i.highlightFile,
  w: i.sizeInMapPx.w,
  h: i.sizeInMapPx.h,
  spots: i.kind === 'task' ? [{ x: i.position[0], y: i.position[1], wall: i.wall }] : i.positions,
}));
const out = '// GENERATED by scripts/gen-icons.mjs from task-icons/task-icons.json. Do not edit by hand.\n'
  + '// Sizes and positions are in design map px (820 x 690). Each PNG has 4 map px of padding (10 for the highlight).\n'
  + `export default ${JSON.stringify(icons)};\n`;
fs.writeFileSync(new URL('../client/src/shared/task-icons.data.js', import.meta.url), out);
console.log(`wrote ${icons.length} icons`);

// Potted plants from task-icons/plants.json. Each sits with its bottom-centre (the pot base) on the given spot.
// Plants are kept out of the open-plan workspaces (the team asked for those floors to stay clear).
const WORKSPACES = [{ x: 372, y: 12, w: 436, h: 233 }, { x: 12, y: 470, w: 392, h: 208 }, { x: 404, y: 470, w: 332, h: 208 }];
const inWorkspace = (p) => WORKSPACES.some((z) => p.x >= z.x && p.x <= z.x + z.w && p.y >= z.y && p.y <= z.y + z.h);
const plantSrc = JSON.parse(fs.readFileSync(new URL('../task-icons/plants.json', import.meta.url), 'utf8'));
const plantIcons = new Map(plantSrc.icons.map((i) => [i.name, i]));
const plants = plantSrc.onMap.filter((p) => !inWorkspace(p)).map((p) => {
  const i = plantIcons.get(p.icon);
  return { file: i.png, x: p.x, y: p.y, w: p.w || i.sizeInMapPx.w, h: p.h || i.sizeInMapPx.h };
});
const plantOut = '// GENERATED by scripts/gen-icons.mjs from task-icons/plants.json. Do not edit by hand.\n'
  + '// Positions are the pot base (bottom-centre) in design map px (820 x 690); the PNGs have no padding.\n'
  + `export default ${JSON.stringify(plants)};\n`;
fs.writeFileSync(new URL('../client/src/shared/plants.data.js', import.meta.url), plantOut);
for (const f of new Set(plants.map((p) => p.file))) {
  fs.copyFileSync(new URL(`../task-icons/${f}`, import.meta.url), new URL(`../client/public/task-icons/${f}`, import.meta.url));
}
console.log(`wrote ${plants.length} plants`);
