// Turns the design team's office-map.json into a module both the server and the client can import.
// Run after replacing map/office-map.source.json:  node scripts/gen-map.mjs
import fs from 'node:fs';
const src = JSON.parse(fs.readFileSync(new URL('../map/office-map.source.json', import.meta.url), 'utf8'));
const out = `// GENERATED by scripts/gen-map.mjs from map/office-map.source.json. Do not edit by hand.\n`
  + `// Units are the design's map px (820 x 690); shared/map.js scales them into world units.\n`
  + `export default ${JSON.stringify(src)};\n`;
fs.writeFileSync(new URL('../client/src/shared/office-map.data.js', import.meta.url), out);
console.log('wrote client/src/shared/office-map.data.js');
